version: 2
updates:

  # Angular app
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'd3'
      - dependency-name: '@types/d3'
      - dependency-name: 'golden-layout'

  # microservice protobuf pseudo-package
  - package-ecosystem: 'npm'
    directory: '/dep/legumeinfo-microservices'
    schedule:
      interval: 'daily'

  # Dockerfile
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
