services:
  nginx-proxy:
    build:
      dockerfile: Dockerfile.nginx-proxy
    environment:
      HTTPS_METHOD: nohttp
      HTTPS_PORT: 8000
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  reverse-proxy:
    environment:
      DEBUG: true
      CERT_NAME: default
      VIRTUAL_HOST: ${DOMAIN}
