services:
  client:
    build:
      context: .
      args:
        CLIENT_SUB_URI: "${CLIENT_SUB_URI:-/}"
        MICROSERVICES_SUB_URI: "${MICROSERVICES_SUB_URI:-http://localhost/gcv/}"
    ports:
      - "${CLIENT_PORT:-80}:80"
    restart: always
