FROM nginxproxy/nginx-proxy:0.10.0-alpine

# https://stackoverflow.com/a/41366949
RUN mkdir -p /etc/nginx/certs \
  && cd /etc/nginx/certs \
  && openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
                -keyout default.key -out default.crt -subj "/CN=gcv.local.gd" \
                -addext "subjectAltName=DNS:gcv.local.gd,IP:127.0.0.1"
