version: '2.4'

services:
  client:
    build: 
      context: client
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - /client/node_modules
      - ./client/src:/client/src

  server:
    build: server
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: '1'
      PGDATABASE: postgres
      PGHOST: db
      PGNAME: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGUSER: postgres
      SECRET_KEY: secret_key
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres -h 127.0.0.1 || exit 1"
      retries: 10
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  redisearch:
    image: redislabs/redisearch:1.6.13
    healthcheck:
      test: "redis-cli ping"

  chado_to_redisearch:
    build: search/database 
    depends_on:
      db:
        condition: service_healthy
      redisearch:
        condition: service_healthy
    command:
      - --pdb=postgres
      - --puser=postgres
      - --ppassword=postgres
      - --phost=db
      - --rhost=redisearch
      - --no-reload

  gene_search:
    build: search/microservices/gene_search
    depends_on:
      - chado_to_redisearch
    expose:
      - "8081"
    command:
      - --no-http
      - --hhost=0.0.0.0
      - --rhost=redisearch


  chromosome_search:
    build: search/microservices/chromosome_search
    depends_on:
      - chado_to_redisearch
    expose:
      - "8082"
    command:
      - --no-http
      - --ghost=0.0.0.0
      - --gport=8082
      - --rhost=redisearch


  chromosome_region:
    build: search/microservices/chromosome_region
    depends_on:
      - chado_to_redisearch
    ports:
      - "8083:8080"
    command:
      - --hhost=0.0.0.0
      - --rhost=redisearch
      - --ghost=0.0.0.0
      - --gport=8084

  search:
    build: search/microservices/search
    depends_on:
      - gene_search
      - chromosome_search
      - chromosome_region
    ports:
      - "8080:8080"
#   environment:
#     GRPC_VERBOSITY: #'debug'
#     GRPC_TRACE: #'all'
    command:
#     - --ghost=0.0.0.0
      - --no-grpc
      - --hhost=0.0.0.0
      - --geneaddr=gene_search:8081
      - --chromosomeaddr=chromosome_search:8082
      - --regionaddr=chromosome_region:8084

