version: '2.4'

services:
  client:
    build: client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always

  server:
    build: server
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: '0'
      PGDATABASE: postgres
      PGHOST: db
      PGNAME: postgres
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      PGPORT: 5432
      PGUSER: postgres
      SECRET_KEY:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "server.wsgi"]

  db:
    build: db
    environment:
      POSTGRES_PASSWORD:
    healthcheck:
      test: "pg_isready -h 127.0.0.1 || exit 1"
      retries: 10
    restart: always

  redisearch:
    image: redislabs/redisearch:1.6.13
    healthcheck:
      test: "redis-cli ping"
    restart: always

  chado_to_redisearch:
    build: search/database 
    depends_on:
      db:
        condition: service_healthy
      redisearch:
        condition: service_healthy
    # load redisearch from chado only once
    restart: on-failure
    command:
      - --pdb=postgres
      - --puser=postgres
      - --ppassword=${POSTGRES_PASSWORD}
      - --phost=db
      - --rhost=redisearch
      - --no-reload

  gene_search:
    build: search/microservices/gene_search
    depends_on:
      - chado_to_redisearch
    restart: always
    expose:
      - "8081"
    command:
      - --no-http
      - --rhost=redisearch


  chromosome_search:
    build: search/microservices/chromosome_search
    depends_on:
      - chado_to_redisearch
    restart: always
    expose:
      - "8081"
    command:
      - --no-http
      - --ghost=0.0.0.0
      - --rhost=redisearch


  chromosome_region:
    build: search/microservices/chromosome_region
    depends_on:
      - chado_to_redisearch
    restart: always
    expose:
      - "8080"
      - "8081"
    command:
      - --hhost=0.0.0.0
      - --rhost=redisearch
      - --ghost=0.0.0.0

  search:
    build: search/microservices/search
    depends_on:
      - gene_search
      - chromosome_search
      - chromosome_region
    restart: always
    expose:
      - "8080"
#   environment:
#     GRPC_VERBOSITY: #'debug'
#     GRPC_TRACE: #'all'
    command:
#     - --ghost=0.0.0.0
      - --no-grpc
      - --hhost=0.0.0.0
      - --geneaddr=gene_search:8081
      - --chromosomeaddr=chromosome_search:8081
      - --regionaddr=chromosome_region:8081

